=== yasintar/taEditable/pbRoutingPercobaan/build/classes/sidnet/models/senseable/mob/MobSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : MobSchema.xsd
    Created on : November 7, 2007, 2:37 PM
    Author     : Oliviu Ghica, Northwestern Unviersity
    Description: Specifies the XML-namespace for Moving Objects in SIDnet
        Purpose of XML Schema document follows.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
  
<xsd:element name="mob">
 <xsd:complexType>
  <xsd:sequence>   
   <xsd:element name="mobProfileName" type="xsd:string"/>
   
   <xsd:element name="fieldDimensions">
       <xsd:complexType>
           <xsd:sequence>
               <xsd:element name="length" type="xsd:integer"/>
               <xsd:element name="width" type="xsd:integer"/>    
           </xsd:sequence>
       </xsd:complexType>
   </xsd:element>
    
   <xsd:element name="radiance" type="xsd:integer"/>
   
   <xsd:element name="timeUnit">
       <xsd:simpleType>
           <xsd:restriction base="xsd:string">
               <xsd:enumeration value="milisecond"/>
               <xsd:enumeration value="second"/>
               <xsd:enumeration value="minute"/>
               <xsd:enumeration value="hour"/>
           </xsd:restriction>
       </xsd:simpleType>
   </xsd:element>
   
   <xsd:element name="periodicity" type="xsd:integer"/> <!-- Specify 0 for infinite loops-->

   <xsd:element name="path">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="locationInTime" maxOccurs="100">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="timeStamp" type="xsd:long"/>
                            <xsd:element name="xCoord" type="xsd:integer"/>
                            <xsd:element name="yCoord" type="xsd:integer"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

     </xsd:sequence>
    </xsd:complexType>
  </xsd:element>  
</xsd:schema>

=== yasintar/taEditable/rrrRouting/src/main/java/sidnet/models/senseable/mob/singleObjectMovingInASquare.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : singleObjectMovingInASquare.xml
    Created on : November 7, 2007, 3:13 PM
    Author     : Oliver
    Description:
        Purpose of the document follows.
-->

<mob 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="MobSchema.xsd">
    <mobProfileName>Single Object Moving in a Square Area</mobProfileName>
    
    <fieldDimensions>
        <length>100</length>
        <width>100</width>
    </fieldDimensions>
    
    <radiance>5</radiance>
    
    <timeUnit>minute</timeUnit>    
    
    <periodicity>0</periodicity>
    
    <path>    
        <locationInTime><timeStamp>0</timeStamp><xCoord>20</xCoord><yCoord>20</yCoord></locationInTime>
        <locationInTime><timeStamp>30</timeStamp><xCoord>80</xCoord><yCoord>20</yCoord></locationInTime> 
        <locationInTime><timeStamp>60</timeStamp><xCoord>80</xCoord><yCoord>80</yCoord></locationInTime>
        <locationInTime><timeStamp>90</timeStamp><xCoord>20</xCoord><yCoord>80</yCoord></locationInTime>
        <locationInTime><timeStamp>120</timeStamp><xCoord>20</xCoord><yCoord>20</yCoord></locationInTime>
    </path>
</mob>

=== yasintar/taEditable/pbRoutingPercobaan/build/classes/sidnet/models/senseable/mob/mobilitytraces/bike/ShiftedToZero_3041bike1.xml
<mob 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="MobSchema.xsd">
          <mobProfileName>ShiftedToZero_3041bike1</mobProfileName>
          
          <radiance>5</radiance>
          
          <timeUnit>millisecond</timeUnit>    
          
          <periodicity>0</periodicity>
          
          <path>    
      
						<locationInTime><timeStamp>0</timeStamp><xCoord>4038.59973573037</xCoord><yCoord>510.495908224024</yCoord></locationInTime>
						<locationInTime><timeStamp>12000</timeStamp><xCoord>3979.66642460879</xCoord><yCoord>496.262957613915</yCoord></locationInTime>
						<locationInTime><timeStamp>26000</timeStamp><xCoord>3938.52430175028</xCoord><yCoord>443.77895223815</yCoord></locationInTime>
						<locationInTime><timeStamp>29000</timeStamp><xCoord>3938.52430175028</xCoord><yCoord>424.653424855322</yCoord></locationInTime>
						<locationInTime><timeStamp>48000</timeStamp><xCoord>3881.81488916157</xCoord><yCoord>334.029559640214</yCoord></locationInTime>
						<locationInTime><timeStamp>63000</timeStamp><xCoord>3838.44886777019</xCoord><yCoord>271.982790570706</yCoord></locationInTime>
						<locationInTime><timeStamp>71000</timeStamp><xCoord>3834.00107070441</xCoord><yCoord>255.303551575169</yCoord></locationInTime>
						<locationInTime><timeStamp>74000</timeStamp><xCoord>3834.00107070441</xCoord><yCoord>248.075881343335</yCoord></locationInTime>
						<locationInTime><timeStamp>88000</timeStamp><xCoord>3871.80734576353</xCoord><yCoord>224.280167041346</yCoord></locationInTime>
						<locationInTime><timeStamp>104000</timeStamp><xCoord>3905.16582375692</xCoord><yCoord>190.810494121164</yCoord></locationInTime>
						<locationInTime><timeStamp>109000</timeStamp><xCoord>3894.04633109245</xCoord><yCoord>164.568491433747</yCoord></locationInTime>
						<locationInTime><timeStamp>120000</timeStamp><xCoord>3786.18725224724</xCoord><yCoord>78.7260080641136</yCoord></locationInTime>
						<locationInTime><timeStamp>127000</timeStamp><xCoord>3750.60487572099</xCoord><yCoord>59.6004806822166</yCoord></locationInTime>
						<locationInTime><timeStamp>130000</timeStamp><xCoord>3726.14199185917</xCoord><yCoord>52.4840053766966</yCoord></locationInTime>
						<locationInTime><timeStamp>138000</timeStamp><xCoord>3650.52944174086</xCoord><yCoord>52.4840053766966</yCoord></locationInTime>
						<locationInTime><timeStamp>152000</timeStamp><xCoord>3544.89426142855</xCoord><yCoord>50.0377169903368</yCoord></locationInTime>
						<locationInTime><timeStamp>156000</timeStamp><xCoord>3517.09552976742</xCoord><yCoord>59.6004806822166</yCoord></locationInTime>
						<locationInTime><timeStamp>163000</timeStamp><xCoord>3478.17730544183</xCoord><yCoord>83.5073899095878</yCoord></locationInTime>
						<locationInTime><timeStamp>185000</timeStamp><xCoord>3340.29559640258</xCoord><yCoord>126.428631594405</yCoord></locationInTime>
						<locationInTime><timeStamp>197000</timeStamp><xCoord>3230.21261902446</xCoord><yCoord>104.968010752462</yCoord></locationInTime>
						<locationInTime><timeStamp>210000</timeStamp><xCoord>3117.90574311346</xCoord><yCoord>42.9212416838855</yCoord></locationInTime>
						<locationInTime><timeStamp>219000</timeStamp><xCoord>3055.6365841925</xCoord><yCoord>0.0</yCoord></locationInTime>
						<locationInTime><timeStamp>224000</timeStamp><xCoord>3030.06175106426</xCoord><yCoord>0.0</yCoord></locationInTime>
						<locationInTime><timeStamp>241000</timeStamp><xCoord>2898.85173762366</xCoord><yCoord>0.0</yCoord></locationInTime>
						<locationInTime><timeStamp>255000</timeStamp><xCoord>2784.32096317977</xCoord><yCoord>2.33509345818311</yCoord></locationInTime>
						<locationInTime><timeStamp>267000</timeStamp><xCoord>2774.31341978176</xCoord><yCoord>2.33509345818311</yCoord></locationInTime>
						<locationInTime><timeStamp>279000</timeStamp><xCoord>2709.82036232791</xCoord><yCoord>7.11647530552</yCoord></locationInTime>
						<locationInTime><timeStamp>316000</timeStamp><xCoord>2428.4971979172</xCoord><yCoord>38.1398598393425</yCoord></locationInTime>
						<locationInTime><timeStamp>330000</timeStamp><xCoord>2347.32490146665</xCoord><yCoord>133.545106899925</yCoord></locationInTime>
						<locationInTime><timeStamp>338000</timeStamp><xCoord>2303.95888007528</xCoord><yCoord>152.670634283684</yCoord></locationInTime>
						<locationInTime><timeStamp>349000</timeStamp><xCoord>2232.79412702276</xCoord><yCoord>131.210013439879</yCoord></locationInTime>
						<locationInTime><timeStamp>355000</timeStamp><xCoord>2199.43564902939</xCoord><yCoord>114.530774444342</yCoord></locationInTime>
						<locationInTime><timeStamp>366000</timeStamp><xCoord>2137.16649010843</xCoord><yCoord>140.772777131759</yCoord></locationInTime>
						<locationInTime><timeStamp>367000</timeStamp><xCoord>2130.49479450978</xCoord><yCoord>143.107870589942</yCoord></locationInTime>
						<locationInTime><timeStamp>370000</timeStamp><xCoord>2109.36775844732</xCoord><yCoord>147.889252437279</yCoord></locationInTime>
						<locationInTime><timeStamp>386000</timeStamp><xCoord>1982.60554207252</xCoord><yCoord>155.005727741867</yCoord></locationInTime>
						<locationInTime><timeStamp>387000</timeStamp><xCoord>1974.8218972074</xCoord><yCoord>155.005727741867</yCoord></locationInTime>
						<locationInTime><timeStamp>393000</timeStamp><xCoord>1932.56782508246</xCoord><yCoord>164.568491433747</yCoord></locationInTime>
						<locationInTime><timeStamp>398000</timeStamp><xCoord>1896.98544855618</xCoord><yCoord>176.466348586604</yCoord></locationInTime>
						<locationInTime><timeStamp>405000</timeStamp><xCoord>1845.83578229968</xCoord><yCoord>198.038164352067</yCoord></locationInTime>
						<locationInTime><timeStamp>409000</timeStamp><xCoord>1810.25340577343</xCoord><yCoord>202.708351272158</yCoord></locationInTime>
						<locationInTime><timeStamp>417000</timeStamp><xCoord>1729.08110932291</xCoord><yCoord>200.373257813044</yCoord></locationInTime>
						<locationInTime><timeStamp>428000</timeStamp><xCoord>1600.09499441522</xCoord><yCoord>195.591875966638</yCoord></locationInTime>
						<locationInTime><timeStamp>442000</timeStamp><xCoord>1428.85480738258</xCoord><yCoord>207.489733117633</yCoord></locationInTime>
						<locationInTime><timeStamp>445000</timeStamp><xCoord>1395.49632938922</xCoord><yCoord>205.154639659449</yCoord></locationInTime>
						<locationInTime><timeStamp>460000</timeStamp><xCoord>1228.70393942243</xCoord><yCoord>226.615260501392</yCoord></locationInTime>
						<locationInTime><timeStamp>482000</timeStamp><xCoord>980.739253005013</xCoord><yCoord>231.396642347798</yCoord></locationInTime>
						<locationInTime><timeStamp>494000</timeStamp><xCoord>899.56695655451</xCoord><yCoord>288.662029569969</yCoord></locationInTime>
						<locationInTime><timeStamp>506000</timeStamp><xCoord>846.193391765104</xCoord><yCoord>353.043892094865</yCoord></locationInTime>
						<locationInTime><timeStamp>516000</timeStamp><xCoord>853.977036630225</xCoord><yCoord>405.527897471562</yCoord></locationInTime>
						<locationInTime><timeStamp>522000</timeStamp><xCoord>829.514152768417</xCoord><yCoord>424.653424855322</yCoord></locationInTime>
						<locationInTime><timeStamp>537000</timeStamp><xCoord>724.990921722536</xCoord><yCoord>458.011902848259</yCoord></locationInTime>
						<locationInTime><timeStamp>543000</timeStamp><xCoord>679.40100179828</xCoord><yCoord>474.802336771041</yCoord></locationInTime>
						<locationInTime><timeStamp>566000</timeStamp><xCoord>464.794793374269</xCoord><yCoord>522.504960303195</yCoord></locationInTime>
						<locationInTime><timeStamp>584000</timeStamp><xCoord>281.323164410758</xCoord><yCoord>555.863438296132</yCoord></locationInTime>
						<locationInTime><timeStamp>585000</timeStamp><xCoord>271.315621012749</xCoord><yCoord>558.309726682492</yCoord></locationInTime>
						<locationInTime><timeStamp>594000</timeStamp><xCoord>181.247730430667</xCoord><yCoord>577.324059139937</yCoord></locationInTime>
						<locationInTime><timeStamp>611000</timeStamp><xCoord>0.0</xCoord><yCoord>577.324059139937</yCoord></locationInTime>
		</path>
</mob>
